<?php /** @var \DpdConnect\Shipping\Block\Adminhtml\System\Config\Header $block */ ?>
<div style="padding:30px;background-color:#f2fcfe ;border-radius:5px;border:1px solid #e8f6fe ;margin-bottom:12px;overflow:auto;">
    <div style="width:63%;float:left;text-align:left;">
        <img src="<?= /* @escapeNotVerified */ $block->getLogo() ?>" style="max-width: 198px;margin-bottom:22px;">
        <p style="margin-bottom:12px;font-size:15px;">DPD Shipping module for Magento2</p>
        <p style="margin-bottom:18px;font-size:12px;">If you have questions about DPD or need support, visit <a href="<?= $block->getSupportUrl() ?>" target="_blank">DPD Benelux</a>.</p>
    </div>
    <div style="width:35%;max-width:285px;float:right;text-align:center;font-size:12px;">
        <a href="<?= /* @escapeNotVerified */ $block->getDocumentationUrl() ?>" target="_blank">
            <div style="background:#fff; border:1px solid #e8f6fe ;margin-bottom:12px;padding:15px;border-top:0;">
                <img src="<?= /* @escapeNotVerified */ $block->getIcon() ?>" style="width:36px;height:36px;margin:0 auto 6px auto;display:block;">
                <strong style="font-weight:bold;text-decoration:none;color:#f77746 ;">DPD Documentation</strong>
            </div>
        </a>
    </div>
</div>
