<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * @var \DpdConnect\Shipping\Block\Adminhtml\Order\Packaging $block
 */
?>
<div id="packaging_window">
    <div class="message message-warning"></div>
    <section class="admin__page-section" id="package_template">
        <div class="admin__page-section-title">
            <span class="title">
                <?= $block->escapeHtml(__('Package')) ?> <span data-role="package-number"></span>
            </span>
            <div class="actions _primary">
                <button type="button"
                        class="action-secondary"
                        data-action="package-save-items">
                    <span><?= $block->escapeHtml(__('Add Selected Product(s) to Package')) ?></span>
                </button>
                <button type="button"
                        class="action-secondary"
                        data-action="package-add-items">
                    <span><?= $block->escapeHtml(__('Add Products to Package')) ?></span>
                </button>
            </div>
        </div>
        <div class="admin__control-table-wrapper admin__page-subsection">
            <table class="data-table admin__control-table">
                <thead>
                    <tr>
                        <th class="col-type"><?= $block->escapeHtml(__('Type')) ?></th>
                        <?php if ($girthEnabled == 1): ?>
                        <th class="col-size"><?= $block->escapeHtml(__('Size')) ?></th>
                        <th class="col-girth"><?= $block->escapeHtml(__('Girth')) ?></th>
                        <th>&nbsp;</th>
                        <?php endif; ?>
                        <th class="col-custom">
                            <?= $block->escapeHtml(__('Customs Value')) ?>
                        </th>
                        <?php if (!$block->displayCustomsValue()): ?>
                            <script type="text/javascript">
                                var elementThCustom = document.querySelector('th.col-custom');
                                if (elementThCustom) {
                                    elementThCustom.style.display = 'none';
                                }
                            </script>
                        <?php endif ?>
                        <th class="col-total-weight"><?= $block->escapeHtml(__('Total Weight')) ?></th>
                        <th class="col-length"><?= $block->escapeHtml(__('Length')) ?></th>
                        <th class="col-width"><?= $block->escapeHtml(__('Width')) ?></th>
                        <th class="col-height"><?= $block->escapeHtml(__('Height')) ?></th>
                        <th>&nbsp;</th>
                        <th>Label type</th>
                        <?php if($block->hasFreshFreezeProducts()): ?>
                        <th class="freshfreeze">Expiration Date</th>
                        <th class="freshfreeze">Description</th>
                        <?php endif; ?>
                        <?php if ($block->getDeliveryConfirmationTypes()): ?>
                        <th class="col-signature"><?= $block->escapeHtml(__('Signature Confirmation')) ?></th>
                        <?php endif; ?>
                        <th class="col-actions">&nbsp;</th>
                    </tr>
                </thead>

                <tbody>
                    <tr>
                        <td class="col-type">
                            <input type="hidden" name="product_type" value="" />
                            <?php $containers = $block->getContainers(); ?>
                            <select name="package_container"
                                    <?php if (empty($containers)): ?>
                                        title="<?= $block->escapeHtmlAttr(__(
                                            'USPS domestic shipments don\'t use package types.'
                                        )) ?>"
                                        disabled=""
                                        class="admin__control-select disabled"
                                    <?php else: ?>
                                        class="admin__control-select"
                                    <?php endif; ?>>
                                <?php foreach ($containers as $key => $value): ?>
                                    <option value="<?= $block->escapeHtmlAttr($key) ?>" >
                                        <?= $block->escapeHtml($value) ?>
                                    </option>
                                <?php endforeach; ?>
                            </select>
                        </td>
                        <?php if ($girthEnabled == 1 && !empty($sizeSource)): ?>
                        <td>
                            <select name="package_size" class="admin__control-select">
                                <?php foreach ($sizeSource as $key => $value): ?>
                                <option value="<?= $block->escapeHtmlAttr($sizeSource[$key]['value']) ?>">
                                    <?= $block->escapeHtml($sizeSource[$key]['label']) ?>
                                </option>
                                <?php endforeach; ?>
                            </select>
                        </td>
                        <td>
                            <input type="text"
                                   class="input-text admin__control-text validate-greater-than-zero"
                                   name="container_girth" />
                        </td>
                        <td>
                            <select name="container_girth_dimension_units"
                                    class="options-units-dimensions measures admin__control-select">
                                <option value="<?= /* @noEscape */ Zend_Measure_Length::INCH ?>" selected="selected" >
                                    <?= $block->escapeHtml(__('in')) ?>
                                </option>
                                <option value="<?= /* @noEscape */ Zend_Measure_Length::CENTIMETER ?>" >
                                    <?= $block->escapeHtml(__('cm')) ?>
                                </option>
                            </select>
                        </td>
                        <?php endif; ?>
                        <?php
                        if ($block->displayCustomsValue()) {
                            $customsValueValidation = ' validate-zero-or-greater ';
                        } else {
                            $customsValueValidation = '';
                        }
                        ?>
                        <td class="col-custom">
                            <div class="admin__control-addon">
                                <input type="text"
                                       class="customs-value input-text admin__control-text <?=
                                       /* @noEscape */ $customsValueValidation ?>"
                                       name="package_customs_value" />
                                <span class="admin__addon-suffix">
                                    <span class="customs-value-currency">
                                        <?= $block->escapeHtml($block->getCustomValueCurrencyCode()) ?>
                                    </span>
                                </span>
                            </div>
                        </td>
                        <?php if (!$block->displayCustomsValue()): ?>
                            <script type="text/javascript">
                                var elementCustom = document.querySelector('td.col-custom');
                                if (elementCustom) {
                                    elementCustom.style.display = 'none';
                                }
                            </script>
                        <?php endif ?>
                        <td class="col-total-weight">
                            <div class="admin__control-addon">
                            <input type="text"
                                   class="options-weight input-text admin__control-text required-entry
                                    validate-greater-than-zero"
                                   name="container_weight" />
                                    <select name="container_weight_units"
                                            class="options-units-weight measures admin__control-select">
                                        <option value="<?= /* @noEscape */ Zend_Measure_Weight::POUND
                                        ?>" selected="selected"  ><?= $block->escapeHtml(__('lb')) ?>
                                        </option>
                                        <option value="<?= /* @noEscape */ Zend_Measure_Weight::KILOGRAM ?>" >
                                            <?= $block->escapeHtml(__('kg')) ?>
                                        </option>
                                    </select>
                                <span class="admin__addon-prefix"></span>
                            </div>
                        </td>
                        <td class="col-length">
                            <input type="text"
                                   class="input-text admin__control-text validate-greater-than-zero"
                                   name="container_length" />
                        </td>
                        <td class="col-width">
                            <input type="text"
                                   class="input-text admin__control-text validate-greater-than-zero"
                                   name="container_width" />
                        </td>
                        <td class="col-height">
                            <input type="text"
                                   class="input-text admin__control-text validate-greater-than-zero"
                                   name="container_height" />
                        </td>
                        <td class="col-measure">
                            <select name="container_dimension_units"
                                    class="options-units-dimensions measures admin__control-select">
                                <option value="<?= /* @noEscape */ Zend_Measure_Length::INCH ?>" selected="selected" >
                                    <?= $block->escapeHtml(__('in')) ?>
                                </option>
                                <option value="<?= /* @noEscape */ Zend_Measure_Length::CENTIMETER ?>" >
                                    <?= $block->escapeHtml(__('cm')) ?>
                                </option>
                            </select>
                        </td>
                        <td>
                            <select name="shipping_product" class="admin__control-select">
                                <option value=""></option>
                                <?php foreach ($block->getLabelTypeOptions() as $shippingProduct): ?>
                                    <option value="<?php echo $shippingProduct['code'] ?>"<?php echo $block->isSelected($shippingProduct) ? ' selected="selected"' : '' ?>>
                                        <?php echo $shippingProduct['name'] ?>
                                    </option>
                                <?php endforeach; ?>
                            </select>
                        </td>
                        <?php if($block->hasFreshFreezeProducts()): ?>
                        <td class="freshfreeze">
                            <input type="date"
                                   class="input-text admin__control-text"
                                   name="expiration_date"
                                   value="<?php echo date('Y-m-d', strtotime('+5 weekdays')) ?>" />
                        </td>
                        <td class="freshfreeze">
                            <input type="text"
                                   class="input-text admin__control-text"
                                   name="goods_description"
                                   maxlength="30" />
                        </td>
                        <?php endif; ?>
                        <?php if ($block->getDeliveryConfirmationTypes()): ?>
                        <td>
                            <select name="delivery_confirmation_types" class="admin__control-select">
                                <?php foreach ($block->getDeliveryConfirmationTypes() as $key => $value): ?>
                                <option value="<?= $block->escapeHtmlAttr($key) ?>" >
                                    <?= $block->escapeHtml($value) ?>
                                </option>
                                <?php endforeach; ?>
                            </select>
                        </td>
                        <?php endif; ?>
                        <td class="col-actions">
                            <button type="button"
                                    class="action-delete DeletePackageBtn">
                                <span><?= $block->escapeHtml(__('Delete Package')) ?></span>
                            </button>
                        </td>
                    </tr>
                </tbody>
            </table>
            <?php if ($block->getContentTypes()): ?>
                <table class="data-table admin__control-table" cellspacing="0">
                    <thead>
                        <tr>
                            <th><?= $block->escapeHtml(__('Contents')) ?></th>
                            <th><?= $block->escapeHtml(__('Explanation')) ?></th>
                        </tr>
                    </thead>
                    <tbody>
                    <tr>
                        <td>
                            <select name="content_type"
                                    class="admin__control-select">
                                <?php foreach ($block->getContentTypes() as $key => $value): ?>
                                    <option value="<?= $block->escapeHtmlAttr($key) ?>" >
                                        <?= $block->escapeHtml($value) ?>
                                    </option>
                                <?php endforeach; ?>
                            </select>
                        </td>
                        <td>
                            <input name="content_type_other"
                                   type="text"
                                   class="input-text admin__control-text options-content-type disabled"
                                   disabled="disabled" />
                        </td>
                    </tr>
                    </tbody>
                </table>
            <?php endif; ?>
        </div>
        <div class="admin__page-subsection" data-role="package-items">
            <div class="grid_prepare admin__page-subsection"></div>
        </div>
    </section>
    <div id="packages_content"></div>

    <script type="text/javascript">
        var elementPackageTemplate = document.querySelector('#package_template');
        if (elementPackageTemplate) {
            elementPackageTemplate.style.display = 'none';
        }
    </script>
    <script>
        require(['jquery'], function($){
            $("div#packages_content").on('click', "button[data-action='package-save-items']",
                function(){packaging.packItems(this)});
            $("div#packages_content").on('click', "button[data-action='package-add-items']",
                function(){packaging.getItemsForPack(this)});
            $("div#packages_content").on('change', "select[name='package_container']",
                function(){
                    packaging.changeContainerType(this);
                    packaging.checkSizeAndGirthParameter(this, 0)
                });
            $("div#packages_content").on('change', "select[name='container_weight_units']",
                function(){packaging.changeMeasures(this)});
            $("div#packages_content").on('change', "select[name='container_dimension_units']",
                function(){packaging.changeMeasures(this)});
            $("div#packages_content").on('click', "button.action-delete.DeletePackageBtn",
                function(){packaging.deletePackage(this)});})
        <?php if ($girthEnabled == 1 && !empty($sizeSource)): ?>
            $("div#packages_content").on('change', "select[name='package_size']",
                function(){packaging.checkSizeAndGirthParameter(this, <?php echo $block->escapeJs($girthEnabled) ?>)});
            $("div#packages_content").on('change', "select[name='container_girth_dimension_units']",
                function(){packaging.changeMeasures(this)});
        <?php endif ?>
        <?php if ($block->getContentTypes()): ?>
            $("div#packages_content").on('change', "select[name='content_type']",
                function(){packaging.changeContentTypes(this)});
        <?php endif; ?>
    </script>
</div>

<script type="text/javascript">
    var elementMessage = document.querySelector('div#packaging_window div.message.message-warning');
    if (elementMessage) {
        elementMessage.style.display = 'none';
    }
</script>
